apiVersion: v1
kind: Service
metadata:
  name: {{ include "pou.fullname" . }}
  labels:
    {{- include "pou.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "pou.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: metrics
      port: 9090
      targetPort: metrics
