apiVersion: v2
name: pulumi-operator-ui
description: >-
  Read-only web UI for Pulumi Kubernetes Operator stacks, their run history and
  diffs.
type: application
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/jalet/pulumi-operator-ui
sources:
  - https://github.com/jalet/pulumi-operator-ui
keywords:
  - pulumi
  - pulumi-kubernetes-operator
  - gitops
  - dashboard
maintainers:
  - name: Joakim Jarsäter
    url: https://github.com/jalet
annotations:
  artifacthub.io/license: Apache-2.0
